title: Ngăn xếp các vấn đề
description: My Personal Stack Problems
author: Nguyễn Văn Hiếu
github: https://github.com/nguyenvanhieu99
about: I'm Programmer for javascript. I've made quite a few web apps, especially on js.
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/vanhieu.cf"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/nguyenvanhieu99"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: Về tác giả
      url: /about/
    - text: Dự án của tôi
      url: /projects/
    - text: XML Feed
      url: /feed.xml
    - text: Chủ đề
      url: /catalog

url: "https://nguyenvanhieu99.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

theme: jekyll-theme-modernist